// Animation names
#define MINI2GUN_ANIM_DEFAULT_ANIMATION 0
#define MINI2GUN_ANIM_WAIT1 1
#define MINI2GUN_ANIM_WAIT2 2
#define MINI2GUN_ANIM_WAIT3 3
#define MINI2GUN_ANIM_WAIT4 4
#define MINI2GUN_ANIM_ACTIVATE 5
#define MINI2GUN_ANIM_DEACTIVATE 6

// Color names

// Patch names

// Names of collision boxes
#define MINI2GUN_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define MINI2GUN_ATTACHMENT_BODY 0
#define MINI2GUN_ATTACHMENT_BARRELS01 1
#define MINI2GUN_ATTACHMENT_BARRELS02 2
#define MINI2GUN_ATTACHMENT_ENGINE 3

// Sound names
